MapScreen and MapBox implementation and API KEY Management
SwEnt-Fall-2024-Group-22/Cyrcle pull request #12
Opened 2024-10-07 20:49 UTC by Pijukai

This is the pull request for the MapBox Api implementation and the implementation of a simple map in `MapScreen.kt` . 
A few dependencies were added, to check that they are correct i invite you to follow the links below which indicates the procedure : 
https://docs.mapbox.com/android/maps/guides/install/

I also invite you to instanciate `MapScreen()` inside `setContent{}` of the `MainActivity.kt` to test properly the map. 

This PR also updates the `gitignore` file which aim to protect the public MapBox API KEY. On this point, i also need your advice about how to manage this API KEY since it does not follow the usual format. Hence i did not committed the Public API key which is needed for the Map to work. 

Note that the MapBox API implemented here support just the Map, navigation and other features are not part of this API but can be build upon it by adding their dependencies.

2024-10-07 21:02 UTC, andrepeiry commented
> it is not very useful at the moment.
Is it required at all at some moment ? Is there a way to ask it only when really necessary (temporary permission) ?

2024-10-07 21:11 UTC, Pijukai commented
It is not required for now but will be for the next Sprint since we will probably address the user localisation permission during it. So would be better to let it pass sonar cloud.

2024-10-07 21:19 UTC, andrepeiry commented on app/build.gradle.kts
Suspicious space at line 150 between `implementation` and the following `(`
`implementation (...` should be replace with `implementation(...`

2024-10-07 21:29 UTC, andrepeiry commented on app/src/main/res/values/mapbox_access_token.xml
This file can be removed, as it is a API key that should not be on the repository.

2024-10-07 21:33 UTC, andrepeiry commented on app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
> +          },
Suspicious and lonely `,` at line 23.

2024-10-07 21:36 UTC, andrepeiry requested changes
Don't forget that a blank line at the end of a file is always nicer than none, thank you for the `MapScreen` example.

2024-10-08 08:04 UTC, Pijukai commented on app/src/main/res/values/mapbox_access_token.xml
Done !

2024-10-08 08:19 UTC, Pijukai commented
@andrepeiry I added the blank spaces at the end of the necessary files but it seems that github doesn't show correctly.

2024-10-08 08:47 UTC, Pijukai commented on app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
> +          },
Fixed

2024-10-08 09:26 UTC, andrepeiry approved these changes
Everything is to my taste, thank for the quick fix

2024-10-08 09:27 UTC, andrepeiry commented
> @andrepeiry I added the blank spaces at the end of the necessary files but it seems that github doesn't show them correctly.

GitHub won't show you the blank line, but it will show a sign if it is missing

2024-10-08 18:03 UTC, Pijukai commented
@andrepeiry  Just add the secret and i think the CI will work. The last commit secured the API KEYs for MapBox in `local.properties`.

2024-10-09 17:38 UTC, LouisJamesVasseur commented
We may need to give further thought/discussion to whether or not we need to give fine-grain location access for further features of our app. For now I agree that it is not needed and coarse-grain is sufficient. Style-based comments were provided by @andrepeiry and I haven't seen any others worth noting. I tested the map and the functioning seems correct

2024-10-09 17:39 UTC, LouisJamesVasseur approved these changes
Everything seems in order and the map displays as expected, so I'll approve this pull request

2024-10-09 17:42 UTC, merged