Implement the Attributes Picker Screen
SwEnt-Fall-2024-Group-22/Cyrcle pull request #93
Opened 2024-10-26 22:06 UTC by sean-prz

_closes #73_

#### Prelude
This PR should only be reviewed and merged after #92 

#### This PR adds the screen to select the attributes.
The user can after having selected the location now set the attributes, and then click submit, the parking spot is then added to the database and the user redirected to the map.

#### How

This PR reuse the drawRectangle function of the map screen that draws the rectangles to show it as a preview in the topBar.
It also adds two customs Composables to make the DropDown Menus an radios buttons that make the core of this AttributesPicker Screen. 

<img width="304" alt="image" src="https://github.com/user-attachments/assets/a46214de-f20b-4d5a-95c5-26732123c5b6">

<img width="488" alt="image" src="https://github.com/user-attachments/assets/5ddc1568-697e-434c-97ed-f67d954a9392">

2024-10-28 12:55 UTC, andrepeiry requested changes
[Blocking] A lot of composable that are in your code could be placed inside `/ui/theme/{atom, molecules}`, mostly the `TextInputField`s and similar objects.
[Note] Your particular `BottomBarAddAttr` could be generalized and moved into `atom, molecules` as well. But that can be done in another PR.

[Blocking] Even thought it is not this PR content (but related as this is the continuum of another), I think `add` is too generic for a package name and doesn't tell anything about its content. It could be improved as `addParking` for example.

[Note] I saw `hasCCTV` in a file. The guideline doesn't specify anything about name convention, but it is good practice to have acronyms also in CamelCase (so the name should be `hasCctv`). In general, it is better to avoid acronym and use whole words, such as `hasVideoSurveillance`

2024-10-28 13:22 UTC, sean-prz commented on app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
> +  fun getUid(): String {
True

2024-10-28 13:53 UTC, AlexandreBeeDeeBop commented on app/src/main/java/com/github/se/cyrcle/ui/add/attributes/AttributesPicker.kt
> +                  question = "Is the parking spots under camera surveillance ?", hasSecurity)
Minor typo

2024-10-28 15:11 UTC, sean-prz commented
> [Blocking] A lot of composable that are in your code could be placed inside `/ui/theme/{atom, molecules}`, mostly the `TextInputField`s and similar objects. [Note] Your particular `BottomBarAddAttr` could be generalized and moved into `atom, molecules` as well. But that can be done in another PR.
> 
> [Blocking] Even thought it is not this PR content (but related as this is the continuum of another), I think `add` is too generic for a package name and doesn't tell anything about its content. It could be improved as `addParking` for example.
> 
> [Note] I saw `hasCCTV` in a file. The guideline doesn't specify anything about name convention, but it is good practice to have acronyms also in CamelCase (so the name should be `hasCctv`). In general, it is better to avoid acronym and use whole words, such as `hasVideoSurveillance`

Thanks for the great review ! Those are all very relevant point, I'm gonna fix them and come back to you

2024-10-29 18:24 UTC, sean-prz commented on app/src/main/java/com/github/se/cyrcle/ui/add/attributes/AttributesPicker.kt
> +                  question = "Is the parking spots under camera surveillance ?", hasSecurity)
Thanks, Fixed with lastest commit

2024-10-29 22:16 UTC, andrepeiry approved these changes
Most of the work has been done, I'll make some minute changes in my PR about the integration of the Atom & Molecules inside the code [not yet created, insert link later], so thank you for your quick work !

2024-10-30 06:16 UTC, merged